[package]
name = "Chess-"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[dependencies]
rand = "0.9.0"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
